defaults:
  - _self_
  - hydra: train
  - dataset: mis
  - model: ${dataset}
  - trainer: ${dataset}
  - generator: train
  - benchmarking: default
  - paths: [common, train]

job_name: mis:default

seed: 2
cuda: 0
num_workers: 10

pretrained_model_path: null



